package com.example.e_queue_booking.models.enums;

public enum Bank_service {
    ACCOUNT_OPENING_AND_SERVICING,
    LENDING,
    DEBIT_AND_CREDIT_CARDS,
    INTERNET_BANKING_AND_MOBILE_APPLICATIONS,
    CURRENCY_EXCHANGE_AND_MONEY_TRANSACTIONS,
    DEPOSITS,
    INVESTMENTS,
    INSURANCE,
    BUSINESS_SERVICE,
    PENSION_PROVISION
}
